#  Raspberry Pi RP2350 MicroROS tests - The ROS Robot Project Research.
#  Copyright 2025 Samyar Sadat Akhavi
#  Written by Samyar Sadat Akhavi, 2025.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https: www.gnu.org/licenses/>.

name: MicroROS CodeQL Analysis

on:
    workflow_call:
        inputs:
            UROS_BUILD_SCRIPT_BRANCH:
                required: true
                type: string
            FIRMWARE_PATH:
                required: true
                type: string
            FREERTOS_KERNEL_IMPORT:
                required: true
                type: string

env:
    FIRMWARE_PATH: ${{inputs.FIRMWARE_PATH}}
    FREERTOS_KERNEL_IMPORT: ${{inputs.FREERTOS_KERNEL_IMPORT}}

jobs:
    analyze_uros:
        name: Analyze MicroROS library
        runs-on: ubuntu-latest
        container: samyarsadat/service_images:microros-build-action-jazzy

        permissions:
            security-events: write
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Copy FreeRTOS Kernel Import File
              shell: bash
              run: |
                  cp "${FIRMWARE_PATH}/${FREERTOS_KERNEL_IMPORT}" \
                  "${FIRMWARE_PATH}/FreeRTOS_Kernel_import.cmake"

            - name: Generate Pico SDK Headers
              uses: samyarsadat/Pico-Build-Action@v1
              with:
                  source_dir: ${{env.FIRMWARE_PATH}}
                  output_dir: "build"
                  cmake_config_only: "true"
                  cmake_args: "-DCMAKE_BUILD_TYPE=Release"

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                  languages: c-cpp
                  build-mode: manual
                  queries: security-extended

            - name: Build MicroROS Library
              id: build
              shell: bash
              run: |
                  apt-get update && apt-get install -y wget
                  wget "https://raw.githubusercontent.com/samyarsadat/MicroROS-Build-Action/${{inputs.UROS_BUILD_SCRIPT_BRANCH}}/entrypoint.sh" -O uros-build.sh
                  wget "https://raw.githubusercontent.com/samyarsadat/MicroROS-Build-Action/${{inputs.UROS_BUILD_SCRIPT_BRANCH}}/install_tools.sh" -O /install_tools.sh
                  chmod +x uros-build.sh && chmod +x /install_tools.sh
                  ./uros-build.sh "${FIRMWARE_PATH}/libmicroros" "src" "micro_ros_setup" ".github/workflows/rp2350_env_setup.sh" \
                                  "false" "my_colcon.meta" "my_toolchain.cmake" ""

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3
              with:
                  category: "pico-source-microros:c-cpp"

            - name: Upload MicroROS Library Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: uros_library_artifacts
                  path: ${{steps.build.outputs.library_build_dir}}
                  if-no-files-found: error